### ISSUE TITLE
1.12 compatability?

### ISSUE THREAD

**Issue by l89669** [caoli5288/SimpleORM#2]
听说spigot团队在1.12已经移除了ebean ORM，是否会导致插件不能使用？
Heard that md_5 has removed ebean ORM on bukkit 1.12, does the change have impact on this project?

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre2-released.240317/

**Comment by caoli5288** [comment]
会。目前还是pre版本，等1.12正式版出来如果依然没有把ebean加回去，就内置个ebean就行了。

**Comment by l89669** [comment]
got it

**Comment by caoli5288** [comment]
Done
