### ISSUE TITLE
梦梦，有个BUG...

### ISSUE THREAD

**Issue by li709854423** [caoli5288/SimpleORM#3]
目前遇到两个BUG，已经找到原因并解决。但没怎么用github，还不知道怎么提交给你，所以这里提出来。。。

第一个问题：MavenLibrary类的getSublist在解析pom文件时，如果第一个节点为注释节点，会直接跳过该pom文件，并不会找到依赖库。
第55行后改为，当找到project节点后再往下走。
           Node pom = XMLHelper.getDocumentBy(xml).getFirstChild();
            while (!pom.getNodeName().equals("project")){
                pom=pom.getNextSibling();
            }

第二个问题是：
在验证MD5时，有一些pom文件是会出现 'md5  xx xxxxx'这样的情况。你直接读第一行然后进行比较会出现问题。
应该改为读一个空格之前的字符串。
代码位置也在上面那个类的isLoadable方法。return改为
return Files.newBufferedReader(check.toPath()).readLine().split(" ")[0].equals(MD5.digest())

**Comment by caoli5288** [comment]
好的，周日回家改。你是把这玩意拿去别的地方用了嘛，

**Comment by li709854423** [comment]
是呀~
